name: Push Kompetansekartlegging 
on:
  push:
    branches:
      - master
jobs:
  push_to_google:
    runs-on: ubuntu-latest
    name: Push 2021 to Google
    steps:
      - uses: actions/checkout@v3
      - name: Generate Config.ts
        env:
          KOMP_CONFIG: ${{ secrets.KOMP_CONFIG_TS }}
        run: |
          echo $KOMP_CONFIG | base64 --decode > 2021/Config.ts
      - uses: daikikatsuragawa/clasp-action@v1.1.0
        with:
          accessToken: ${{ secrets.KOMP_ACCESS_TOKEN }}
          idToken: ${{ secrets.KOMP_ID_TOKEN }}
          refreshToken: ${{ secrets.KOMP_REFRESH_TOKEN }}
          clientId: ${{ secrets.KOMP_CLIENT_ID }}
          clientSecret: ${{ secrets.KOMP_CLIENT_SECRET }}
          scriptId: ${{ secrets.KOMP_SCRIPT_ID }}
          rootDir: '2021'
          command: 'push'
